### ISSUE TITLE
Add EU server for Zergpool

### ISSUE THREAD

**Issue by tr1l3r** [nemosminer/NemosMiner-v2.5.2-windows#340]
Hi. Can you add Europe server for Zergpool? It's been released by the Zergpool.

**Comment by nemosminer** [comment]
sure thankyou

**Comment by Nickduino** [comment]
What's the location in the bat file, then? EU or Europe?

**Comment by nemosminer** [comment]
i'll sort that 2moro sorry for delay been very busy last few days

**Comment by tr1l3r** [comment]
No worries m8. I know you got a lot to work on.

**Comment by nemosminer** [comment]
done you need to edit startzergpool.bat and change -Location and -Poolname 

eg. startzergpoolplus.bat

powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\NemosMinerv2.5.1.ps1 -SelGPUDSTM '0 1' -SelGPUCC '0,1' -Currency USD -Passwordcurrency BTC -Wallet 1QGADhdMRpp9Pk5u5zG1TrHKRrdK5R81TE -Location Europe -ActiveMinerGainPct 3 -PoolName zergpoolpluseu -WorkerName ID=NemosMinerv2.5.1 -Type nvidia -Algorithm hsr,xevan,skunk,tribus,phi,c11,skein,groestl,sib,bitcore,x17,Nist5,MyriadGroestl,Lyra2RE2,neoscrypt,blake2s,lyra2z
