### ISSUE TITLE
New x17 miner

### ISSUE THREAD

**Issue by ErsinErce** [nemosminer/NemosMiner-v2.5.2-windows#353]
https://github.com/Enemy-Mine/ccminer/releases/tag/v1.03-RVN

x17 5% increase mining on my rig

**Comment by nemosminer** [comment]
i'll test 2moro thank you 

got this one to test as well : https://github.com/MSFTserver/ccminer/releases

**Comment by UselessGuru** [comment]
Be careful with https://github.com/Enemy-Mine/ccminer/releases/tag/v1.03-RVN.

Might me malware. [see this](https://github.com/Enemy-Mine/ccminer/issues/4)

**Comment by nemosminer** [comment]
thanks yeh just looked into a bit more, he has no source code available so i won't be touching it... 

i'll test and add https://github.com/MSFTserver/ccminer/releases 

but not https://github.com/Enemy-Mine/ccminer/releases/tag/v1.03-RVN.

**Comment by ErsinErce** [comment]
https://bitcointalk.org/index.php?topic=2752467.msg31603074#msg31603074

yep, don't download,
sorry i didn't search after seen this website http://cryptomining-blog.com/9507-ccminer-enemy-1-03-fork-for-raven-rvn-mining-now-available/

**Comment by nemosminer** [comment]
done
