### ISSUE TITLE
HELP REQUIRED TO SETUP MULTI POOL

### ISSUE THREAD

**Issue by jeetbarman** [nemosminer/NemosMiner-v2.5.2-windows#357]
Is algorithm not switching because -ActiveMinerGainPct < 3% or there is some other reason?

![image](https://user-images.githubusercontent.com/36787233/36998478-14d216c4-20e3-11e8-8d2f-e43b0d1d50cf.png)

If I want to use Zergpool with auto exchange to LTC what modification need to be done on startup file?

Since there is no single startup file for multiple pool hence adding -PoolName miningpoolhub, zergpool  and giving -Passwordcurrency LTC -Wallet <LTC Wallet Address> will work?

**Comment by nemosminer** [comment]
yeh

**Comment by jeetbarman** [comment]
@nemosminer Shall I give my LTC wallet address under -Wallet as MiningPoolHub doesn't use wallet address?

**Comment by nemosminer** [comment]
-wallet "your litecoinwallet" 
-Passwordcurrency LTC

also you will have to edit your account @ mining pool hub and change auto convert to LTC

**Comment by jeetbarman** [comment]
@nemosminer For mining pool hub it's marked as Litecoin under Auto Exchange and since MPH use worker name there seem to be no issue  but for zergpoolplus it's not working as values are in BTC.

Also pool are not loading up for zergepool.

![image](https://user-images.githubusercontent.com/36787233/36999996-e4d5d168-20e7-11e8-83f4-9451e5fa6a73.png)


![image](https://user-images.githubusercontent.com/36787233/36999979-d9c37280-20e7-11e8-8fdd-e5e136e64262.png)
![image](https://user-images.githubusercontent.com/36787233/37000117-5c89874a-20e8-11e8-9d07-2debe6e9669e.png)
