### ISSUE TITLE
Re-enable CCMinerKlaust?

### ISSUE THREAD

**Issue by Crasha** [nemosminer/NemosMiner-v2.5.2-windows#362]
Hi,

HSRMiner keeps crashing on me with some CUDA error, and I've found that the CCMinerKlaust software is a lot more stable. I noticed it was disabled in favour of HSRMiner and was wondering what I need to do if I'd like to re-enable it? 

Thanks,
Crash

**Comment by nemosminer** [comment]
edit Miners/CcminerKlaust.ps1 

remove # from neoscrypt

eg. . .\Include.ps1

$Path = ".\Bin\NVIDIA-CcminerKlaust\ccminer.exe"
$Uri = "https://github.com/KlausT/ccminer/releases/download/8.20/ccminer-820-cuda91-x64.zip"

$Commands = [PSCustomObject]@{
    #"bitcore" = "" #Bitcore
    #"blake2s" = "" #Blake2s
    #"blakecoin" = "" #Blakecoin
    #"vanilla" = "" #BlakeVanilla
    #"cryptonight" = "" #Cryptonight
    #"decred" = "" #Decred
    #"equihash" = "" #Equihash
    #"ethash" = "" #Ethash
    #"groestl" = " -d $SelGPUCC" #Groestl
    #"hmq1725" = "" #hmq1725
    #"keccak" = "" #Keccak
    #"lbry" = "" #Lbry
    #"lyra2v2" = " -d $SelGPUCC" #Lyra2RE2
    #"lyra2z" = "" #Lyra2z
    #"myr-gr" = " -d $SelGPUCC" #MyriadGroestl
    "neoscrypt" = " -b 4068 -d $SelGPUCC" #NeoScrypt
    #"nist5" = " -d $SelGPUCC" #Nist5
    #"pascal" = "" #Pascal
    #"qubit" = "" #Qubit
    #"scrypt" = "" #Scrypt
    #"sia" = "" #Sia
    #"sib" = "" #Sib
    #"skein" = "" #Skein
    #"timetravel" = "" #Timetravel
    #"x11" = "" #X11
    #"veltor" = "" #Veltor
    #"x11evo" = "" #X11evo
    #"x17" = "" #X17
    #"yescrypt" = "" #Yescrypt
}
