### ISSUE TITLE
Benchmark Miningpool problems

### ISSUE THREAD

**Issue by Riones** [nemosminer/NemosMiner-v2.5.2-windows#364]
Hi.
I need your help, why don't benchmarking all algo's?

See this picture please...
![nemos_miningpool](https://user-images.githubusercontent.com/36863608/37050916-0e27f7e6-216d-11e8-9b40-883c09c1154d.jpg)

Thank you.

**Comment by nemosminer** [comment]
because miningpoolhub doesn't support any of those algos....

**Comment by Riones** [comment]
Thank you.
And Sib support? Because give me an error of connection.

Thank you
