### ISSUE TITLE
Miningpool Hub Vs Zergpool

### ISSUE THREAD

**Issue by Riones** [nemosminer/NemosMiner-v2.5.2-windows#366]
Hi!
This is normal, the diference with EUR/day?
Or I have something wrong?

Miningpool Hub 
![nemos_miningpool](https://user-images.githubusercontent.com/36863608/37062116-7068c802-218d-11e8-9be5-08b86e2d6d13.jpg)

ZergPool
![nemos_zergpool](https://user-images.githubusercontent.com/36863608/37062134-7a79c7a6-218d-11e8-8551-ad73b6a5f209.jpg)

Thank you.

**Comment by nemosminer** [comment]
normal
