### ISSUE TITLE
X16r algo issue on gtx1060 and 1070

### ISSUE THREAD

**Issue by tr1l3r** [nemosminer/NemosMiner-v2.5.2-windows#368]
Yo Nemo. I've tested x16r algo on 2x970 and it's working flawlessly. But it crashes on a rig with 1060 and 1070. Did you test it yourself? Btw, algo is crazy profitable compared to others on Zergpool. There seems to be a little problem with Zergpool on Eu. It just doesn't seems to sync well with profitability values when compared with site's values. I'm using Zergpool plus. Awesome job so far m8. Keep it up.

**Comment by MrPlusGH** [comment]
Try to decrease intensity in the miner file.
x16r works well with default settings. I just have on 1080 which crashes with default intensity and works fine with -i 19

**Comment by tr1l3r** [comment]
Well intensity is set to i19 but I don't even know where to change it. Would appreciate if you can explain a little bit.

**Comment by MrPlusGH** [comment]
Edit \Miners\CcminerTpruvotx64.ps1
Change
    "x16r" = " -d $SelGPUCC --api-remote --api-allow=0/0" #X16r
to
    "x16r" = " -i 19 -d $SelGPUCC --api-remote --api-allow=0/0" #X16r
Adjust the value with the intensity you want.

**Comment by tr1l3r** [comment]
Wow. I would have never been able to do this on my on. Thanx a lot m8. You rock.

**Comment by tr1l3r** [comment]
But can I change the intensity just for one spesific gpu? There is only one that crashes. The others are fine.

**Comment by nemosminer** [comment]
yeh i tested it on 1060 and 1070 it works great not sure why its not for you...  i'll add intensity command to x16r today which will fix that

**Comment by nemosminer** [comment]
eg.

. .\Include.ps1

$Path = ".\Bin\NVIDIA-TPruvotx64\ccminer-x64.exe"
$Uri = "https://github.com/MSFTserver/ccminer/releases/download/2.2.5-rvn/ccminer-x64-2.2.5-rvn-cuda9.7z"

$Commands = [PSCustomObject]@{
    #"phi" = " -d $SelGPUCC" #Phi
    #"bitcore" = " -d $SelGPUCC" #Bitcore
    #"jha" = " -d $SelGPUCC" #Jha
    #"blake2s" = " -d $SelGPUCC" #Blake2s
    #"blakecoin" = " -d $SelGPUCC" #Blakecoin
    #"vanilla" = "" #BlakeVanilla
    #"cryptonight" = " -i 10.5 -l 8x120 --bfactor=8 -d $SelGPUCC --api-remote" #Cryptonight
    #"decred" = "" #Decred
    #"equihash" = "" #Equihash
    #"ethash" = "" #Ethash
    #"groestl" = " -d $SelGPUCC" #Groestl
    #"hmq1725" = " -d $SelGPUCC" #hmq1725
    #"keccak" = "" #Keccak
    #"lbry" = " -d $SelGPUCC" #Lbry
    #"lyra2v2" = "" #Lyra2RE2
    "lyra2z" = " -d $SelGPUCC --api-remote --api-allow=0/0 --submit-stale" #Lyra2z
    #"myr-gr" = "" #MyriadGroestl
    #"neoscrypt" = " -d $SelGPUCC" #NeoScrypt
    #"nist5" = "" #Nist5
    #"pascal" = "" #Pascal
    #"qubit" = "" #Qubit
    #"scrypt" = "" #Scrypt
    #"sia" = "" #Sia
    #"sib" = "" #Sib
    #"skein" = "" #Skein
    #"skunk" = " -d $SelGPUCC" #Skunk
    #"timetravel" = " -d $SelGPUCC" #Timetravel
    #"tribus" = " -d $SelGPUCC" #Tribus
    #"x11" = "" #X11
    #"veltor" = "" #Veltor
    #"x11evo" = " -d $SelGPUCC" #X11evo
    #"x17" = " -d $SelGPUCC" #X17
    "x16r" = " -i 19 -d $SelGPUCC --api-remote --api-allow=0/0" #X16r
}

**Comment by tr1l3r** [comment]
Got the algo to work. Gj Nemo. Had to set intensity to 21, but no the profitability of the algo is shit. But it won't work on smaller intensity. Got one more question. Does smaller intensity mean bigger hashrate? I don't really get the whole intensity thing. Could you also check for zerpoolplus on EU Nemo. The profitability numbers don't change even thoug one algo becomes completelly unprofitable.

**Comment by tiotoi** [comment]
hi Nemo, i did everything but got an error
<img width="1345" alt="screen shot 2018-03-08 at 6 01 41 pm" src="https://user-images.githubusercontent.com/9711334/37181420-e965ec30-22fa-11e8-8091-b400b16a4c0d.png">

**Comment by buxstore** [comment]
what pool you are mining？
