### ISSUE TITLE
stats of runned miners and % of time on pools

### ISSUE THREAD

**Issue by CaHek83** [nemosminer/NemosMiner-v2.5.2-windows#374]
Please bring back status of runned miners like in older versions like 2.2.1 when we can see how many times and how long miners have been working its very useful
And second i want to ask, make calculation of % of time on pools.

**Comment by nemosminer** [comment]
its all still there in the logs folder after you run......

**Comment by CaHek83** [comment]
or just use timer and calculator and calculate this all ourself! great job Nemo!
