### ISSUE TITLE
x16r unstable

### ISSUE THREAD

**Issue by gak45** [nemosminer/NemosMiner-v2.5.2-windows#375]
x16r seems to be unstable with 1080tis. Usually with ccminer I would just lower the intensity... but it seems to be ignoring the '-i' setting.  Any help on config'ing it to work 'properly' with nemosminer?

**Comment by nemosminer** [comment]
use ccminer enemy 1.03....

add the ccminerenemy.ps1 to miners folder.. : https://github.com/nemosminer/ccminerrvnenemyps1/archive/master.zip

run NemosMiners to download miners you will get a error saying ccminer enemy does not exist, close 

In NemosMiner folder find the new Bin Folder add a new folder in there called NVIDIA-ccminer

then download ccminerenemy 1.03 : https://mega.nz/#!JDAm3TJb!BMQPYJz5_nmkZEZB0UUwWicopIdgnHG82Ht5buWxZxo

you will have to extract contents fond ccminer.exe and copy and paste it into folder NVIDIA-ccminer

re run NemosMiner ccminerenemy will now be enabled for x17, and x16r algos 

Best Regards
Nemo

**Comment by gak45** [comment]
Thanks! I was investigating x16r problems and yeah that is the best option. Too bad it is MIA on github as I didnt want to DL it from someone I didnt trust. I trust you though. :) 

Thanks mate. Will bump up the donation setting as I try and support peeps that really help out the miner community.
