### ISSUE TITLE
conversion to linux system?

### ISSUE THREAD

**Issue by ebojali** [nemosminer/NemosMiner-v2.5.2-windows#376]
Hi, 

There is quite a straight forward way to install powershell on any linux running system. Below is an exact procedure:

# Import the public repository GPG keys
curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -

# Register the Microsoft Ubuntu repository
curl https://packages.microsoft.com/config/ubuntu/17.04/prod.list | sudo tee /etc/apt/sources.list.d/microsoft.list

# Update the list of products
sudo apt-get update

# Install PowerShell
sudo apt-get install -y powershell

# Start PowerShell
pwsh

Perhaps you can convert the bat files into a shell .sh file and try converting the miner to linux?

**Comment by nemosminer** [comment]
https://github.com/nemosminer/NemosMiner-v2.5.2-linux-HIVE-OS

: )

**Comment by ebojali** [comment]
Not sure I understand, I need Hive-OS for it or?
