### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by gak45** [nemosminer/NemosMiner-v2.5.2-windows#377]
Will you be adding in NPlus' GUI option in the future -like you did the plus pools? Its an interesting idea... and maybe you can make it work so it doesnt have to restarted for changes to config to be implemented!

**Comment by nemosminer** [comment]
looking into it v.2.5.2 is about to be release i have added a brand new RavenMiner different from ccminer tpruvot and ccminer enemy 

i'll start testing GUI over coming days if all goes well we will be upgrading to v3.0 soon

**Comment by MrPlusGH** [comment]
Can I help in any way?
